- name: Destroy EC2 Instances
  hosts: localhost
  connection: local
  vars_files:
    - vars/vars.yaml

  tasks:
    - name: Load instance details from JSON file
      ansible.builtin.include_vars:
        file: "{{ output_dir }}/{{ output_file }}"
        name: ec2_instances

    - name: Terminate EC2 instances
      amazon.aws.ec2_instance:
        instance_ids: "{{ item.instances[0].instance_id }}"
        state: absent
        wait: true
      loop: "{{ ec2_instances.results }}"
