name: "ew-deploy-01"

on:
 push:
   branches:
    - main
   paths:
   - "terraform_dev/**"
 
 workflow_dispatch:

jobs:
  terraform-plan:
    uses: K-Basavaraj/Ansible-ec2-instance/.github/workflows/rw-terraform-plan-01.yaml@main
    with:
      path: ansible-server
      key: ansible-server.tfstate
      bucket: remotes3-githubcicd
      region: us-east-1
      dynamodb_table: githubciddbtable
    secrets:
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}

  approve-and-apply:
    uses: .github/workflows/rw-terraform-apply-01.yml@main
    needs: [terraform-plan]
    with:
      path: ansible-server
      key: "ansible-server/terraform.tfstate"
      bucket: "your-bucket-name"
      region: "ap-south-1"
      dynamodb_table: "your-lock-table"
      github_environment: auth-Apply
    secrets:
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
   