name: "ew-deploy-01"

on:
 push:
   branches:
    - main
   paths:
    - "ansible-server/**"
 
 workflow_dispatch:

jobs:
  terraform-plan:
    uses: K-Basavaraj/Ansible-ec2-instance/.github/workflows/rw-terraform-plan-01.yaml@main
    with:
      path: ansible-server
      tf_version: latest
      key: ansible-server.tfstate
      bucket: remotes3-githubcicd
      region: us-east-1
      dynamodb_table: githubciddbtable
    secrets:
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}

  approve-and-apply:
    uses: K-Basavaraj/Ansible-ec2-instance/.github/workflows/rw-terraform-apply-01.yaml@main
    needs: [terraform-plan]
    with:
      path: ansible-server
      tf_version: latest
      key: ansible-server.tfstate
      bucket: remotes3-githubcicd
      region: us-east-1
      dynamodb_table: githubciddbtable
      github_environment: auth-Apply # environment protected with manual approval
    secrets:
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
   