# name: "ew-intgration-01.yaml"

# on:
#   pull_request:
#     types: [opened, reopened, synchronize]
#     branches:
#       - main
#     paths:
#       - "ansible-server/**"
# permissions:
#   id-token: write
#   contents: write
#   pull-requests: write

# jobs:
#   validate:
#     uses: K-Basavaraj/terraformworkspace/.github/workflows/rw-oidc-validate.yml@main
#     with:
#       path: terraform_dev
#       tf_version: latest
#     secrets:
