name: "rw-terraform-apply-01"

on:
  workflow_call:
    inputs:
      path:
        required: true
        type: string
      key:
        required: true
        type: string
      bucket:
        required: true
        type: string
      region:
        required: true
        type: string
      dynamodb_table:
        required: true
        type: string
      github_environment:
        description: 'specify the github environment'
        required: true
        type: string
      tf_version:
        description: "Specify the version of the terraform to use"
        required: true
        type: string

    secrets:
      AWS_ACCESS_KEY_ID:
        required: true
      AWS_SECRET_ACCESS_KEY:
        required: true

jobs:
  terraform-apply:
    runs-on: ubuntu-latest
    environment: ${{ inputs.github_environment}}
    defaults:
      run:
        shell: bash
        working-directory: ${{ inputs.path }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v3

      - name: Download Plan Artifact
        uses: actions/download-artifact@v4
        with:
          name: plan-artifact
          path: ./tfplan-folder

      - name: Terraform Init with AWS S3 Backend
        run: |
          terraform init \
            -backend-config="bucket=${{ inputs.bucket }}" \
            -backend-config="key=${{ inputs.key }}" \
            -backend-config="region=${{ inputs.region }}" \
            -backend-config="dynamodb_table=${{ inputs.dynamodb_table }}"

        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}

      - name: Terraform Apply
        run: terraform apply -auto-approve tfplan-folder/plan.tfplan
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
