name: "rw-terraform-validate-01"

on:
  workflow_call:
    inputs:
      path:
        description: "Specify the path of the root Terraform module"
        required: true
        type: string
      tf_version:
        description: "Specify the version of the terraform to use"
        required: true
        type: string
    
    secrets:
        AWS_ACCESS_KEY_ID:
          required: true
        AWS_SECRET_ACCESS_KEY:
          required: true
jobs:
  validate:
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash
        working-directory: ${{ inputs.path }}
    permissions:
      id-token: write
      contents: write
      pull-requests: write
   

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: ${{ inputs.tf_version }}

      - name: Terraform Init
        run: terraform init -backend=false

      - name: Terraform Format
        run: terraform fmt --check
        continue-on-error: false

      - name: Terraform Validate
        run: terraform validate
        continue-on-error: false
